MVCProjectExample.UI/MVCProjectExample.UI/Controllers/AzureCosmosDBController.cs
using MVCBsuinessEntities;
using MVCProjectExample.DataAccessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCProjectExample.Common;
using System.Threading.Tasks;
using MVCProjectExample.UI.ActionFilter;
using MVCProjectExample.BAL.Domain;
using Ninject;

namespace MVCProjectExample.UI.Controllers
{
     
    public class AzureCosmosDBController : Controller
    {
        private readonly INomineeDetails _nomineeDetails = null;
        public AzureCosmosDBController([Named("NomineeCustomerSiblingDetails")]INomineeDetails nomineeDetails)
        {
            this._nomineeDetails = nomineeDetails;
        }


        public ActionResult Index()
        {
            return View();
        }

        // GET: AzureCosmosDB
        [HttpPost]
        [ActionName("CreateFund")]
        public async Task<ActionResult> FundDetailsPost(Funds _fundDetails)
        {
            var result = await new AzureCosmosDB<Funds>().Init(CollectionName.Funds);
            result.InsertFundDocuments(_fundDetails);
            return View();
        }

        [HttpGet]
        [ActionName("GetFund")]
        public async Task<JsonResult> GetFundDetails()
        {
            return Json((await new AzureCosmosDB<Funds>().Init(CollectionName.Funds)).GetFundDocuments(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetNomineeDetails()
        {
            return View(this._nomineeDetails.GetCustomerNomineeDetails());
        }
    }
}

MVCProjectExample.UI/MVCProjectExample.UI/Controllers/DIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjectExample.UI.Controllers
{
    public class DIController : Controller
    {
        // GET: DI
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVCProjectExample.UI/MVCProjectExample.UI/Controllers/MultipleViewController.cs
using MVCProjectExample.BAL.Domain;
using MVCProjectExample.UI.DataAccessLayer;
using Ninject;
using System.Web.Mvc;

namespace MVCProjectExample.UI.Controllers
{
    public class MultipleViewController : Controller
    {
        private readonly DAL _dataAccessLayer = null;
        private readonly INomineeDetails _nomineeDetails = null;
        public MultipleViewController([Named("NomineeDetails")]INomineeDetails nomineeDetails)
        {
            this._nomineeDetails = nomineeDetails;
            _dataAccessLayer = new DAL();
        }
        // GET: MultipleView
        public ActionResult Index()
        {
            var _dataAcessLayer = new DAL();
            ViewBag.Message = "Welcome to Multiple View Example Application Using Tuple";

            /*
                Creating the Expando Objects in CSharp
            */
            /*
                dynamic _myModel = new ExpandoObject();
                _myModel.Teacher = _dataAcessLayer.GetTeachers();
                _myModel.Student = _dataAcessLayer.GetStudent();
            */


            /*
                Creating the Custom View Model
            */
            /*
                var _viewModel = new CustomViewModel();
                _viewModel.Teacher = _dataAcessLayer.GetTeachers();
                _viewModel.Student = _dataAcessLayer.GetStudent();

            */

            /*
                Creating the View Data Example 
            */
            /*
                ViewData["Teachers"] = _dataAcessLayer.GetTeachers();
                ViewData["Students"] = _dataAcessLayer.GetStudent();
            */

            /*
                Creating the Object Using Tuple
            */
            /*
                var _TupleModel = new Tuple<List<Teacher>, List<Student>>
                (_dataAcessLayer.GetTeachers(), _dataAcessLayer.GetStudent());

            */



            return View();
        }

        public ActionResult ExamplePartial()
        {
            ViewBag.Message = "Welcome to the Demonstration of Partial View Example";
            return View();
        }


        public PartialViewResult RenderTeacher()
        {
            return PartialView(_dataAccessLayer.GetTeachers());
        }

        public PartialViewResult RenderStudent()
        {
            return PartialView(_dataAccessLayer.GetStudent());
        }

        public PartialViewResult RenderDepartment()
        {
            return PartialView(_dataAccessLayer.GetDepartment());
        }

        public ActionResult CustomDirective()
        {
            return View();
        }

        public ActionResult CustomerNomineeDetails()
        {
            return View(this._nomineeDetails.GetCustomerNomineeDetails());
        }
    }
}

MVCProjectExample.UI/MVCProjectExample.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title Sachin Mishra Azure Application</title>>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sachin Mishra", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Home", "CustomDirective", "MultipleView", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Northwind", "ViewNorthWind", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Azure Cosmos DB", "Index", "AzureCosmosDB", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Azure Cosmos DB", "Index", "AzureCosmosDB", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Dependency Injection", "Index", "DI", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sachin Mishra Azure Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>